apiVersion: v1
kind: ConfigMap
metadata:
  name: cubtera-example
  labels:
    app.kubernetes.io/name: cubtera-example
data:
  region: {{ .Values.region | quote }}
  environment: {{ .Values.environment | quote }}
