use log::{debug, info, warn};
use rand::Rng;
use serde_json::{json, Value};
use std::collections::HashMap;
use std::io::Write;
use std::net::TcpListener;
use std::path::PathBuf;
use std::process::Command;
use yansi::Paint;

mod tfswitch;

use super::{Runner, RunnerLoad};
use crate::prelude::*;
use tfswitch::tf_switch;

pub struct TfRunner {
    load: RunnerLoad,
    ctx: Value,
}

impl Runner for TfRunner {
    fn new(load: RunnerLoad) -> Self {
        let ctx = Value::Object(serde_json::Map::new());
        TfRunner { load, ctx }
    }

    fn get_load(&self) -> &RunnerLoad {
        &self.load
    }

    fn get_ctx(&self) -> &Value {
        &self.ctx
    }

    fn get_ctx_mut(&mut self) -> &mut Value {
        &mut self.ctx
    }

    fn copy_files(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        info!(target: "tf runner", "Copy files to: {}", &self.load.unit.temp_folder.to_string_lossy().blue());

        match self.load.command.first() {
            Some(command) if command == "init" => {
                self.load.unit.remove_temp_folder();
                self.load.unit.copy_files();
                self.create_state_backend()?;
            }
            _ => {
                if !self.load.unit.temp_folder.exists() {
                    exit_with_error(format!(
                        "Can't find unit temp folder {:?}. Run init command first.",
                        &self.load.unit.temp_folder
                    ));
                }
                if GLOBAL_CFG.always_copy_files {
                    self.load.unit.copy_files();
                    self.create_state_backend()?;
                }
            }
        }

        Ok(())
    }

    fn change_files(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        debug!(target: "tf runner", "Convert dims data files into terraform format");

        // read all files started with dim_ and json extension
        let files = std::fs::read_dir(&self.load.unit.temp_folder)
            .unwrap_or_exit(format!(
                "Can't read unit temp folder: {:?}",
                self.load.unit.temp_folder
            ))
            .filter_map(|entry| entry.ok())
            .map(|entry| entry.path())
            .filter(|entry| entry.is_file())
            .filter(|entry| entry.extension().unwrap_or_default() == "json")
            // .filter(|entry| entry.file_stem().unwrap_or_default().to_str().unwrap_or_default().starts_with("dim_"))
            .filter(|entry| {
                entry
                    .file_stem()
                    .unwrap_or_default()
                    .to_str()
                    .unwrap_or_default()
                    .starts_with("cubtera_")
            })
            .filter(|entry| {
                !entry
                    .file_stem()
                    .unwrap_or_default()
                    .to_str()
                    .unwrap_or_default()
                    .contains(".auto.tfvars")
            })
            .collect::<Vec<PathBuf>>();

        // for each file read json as value and create list of root keys
        #[allow(clippy::format_collect)]
        if !files.is_empty() {
            let dim_tf_variables: String = files
                .iter()
                .filter_map(read_json_file)
                .filter_map(|json: serde_json::Value| json.as_object().map(|obj| obj.to_owned()))
                .flat_map(|obj| obj.into_iter().map(|(k, _)| k))
                .map(|key| {
                    format!(
                        r#"variable "{}" {{
    type        = any
    default     = null
    description = "Generated by Cubtera"
}}
"#,
                        key
                    )
                })
                .collect();

            let mut file =
                std::fs::File::create(self.load.unit.temp_folder.join("cubtera_vars.tf"))?;
            file.write_all(dim_tf_variables.as_bytes())?;
        }

        // rename all files to dim_<dim_name>.auto.tfvars.json
        files.iter().for_each(|file| {
            let new_file = file.with_file_name(format!(
                "{}.auto.tfvars.json",
                file.file_stem().unwrap_or_default().to_string_lossy() //.trim_start_matches("dim_")
            ));
            std::fs::rename(file, new_file)
                .unwrap_or_exit(format!("Can't rename file: {:?}", file));
        });

        Ok(())
    }

    fn runner(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        let mut tf_args: Vec<String> = Vec::new();

        if let Some(command) = self.load.command.first() {
            match command.as_str() {
                "plan" | "apply" | "destroy" | "refresh" | "console" | "import" => {
                    // check if unit temp folder is not empty
                    if !self.load.unit.temp_folder.exists() {
                        exit_with_error(format!(
                            "Can't find unit temp folder {:?}. Run init command first.",
                            &self.load.unit.temp_folder
                        ));
                    }
                    // extend vars with required env vars from unit manifest
                    tf_args.extend(self.tf_vars_args());
                }
                _ => {}
            }
        }

        // TODO: Remove legacy spec after units lib is fixed and remove params var usage
        let mut params = self.load.params.clone();
        if self.load.unit.manifest.runner.is_none() {
            if let Some(spec) = &self.load.unit.manifest.spec {
                if let Some(version) = &spec.tf_version {
                    params.version = version.clone();
                    params.runner_command = None;
                    warn!(target: "tf runner", "{}: TF version is defined with {} in unit_manifest. \
                    Use {} instead.", "DEPRECATED".red(), "spec.tf_version".red(), "runner.version".blue());
                }
            }
        }

        let tf_path = match params.runner_command {
            Some(bin_path) => {
                info!(target: "tf runner", "Use custom binary path...");
                string_to_path(&bin_path)
            }
            None => {
                info!(target: "tf runner", "Run terraform version {}", &params.version.yellow());
                tf_switch(&params.version).unwrap_or_exit(format!(
                    "Failed to switch to terraform version {}",
                    params.version
                ))
            }
        };

        if let Some(extra_params) = &self.load.params.extra_args {
            tf_args.extend(extra_params.split(" ").map(|s| s.to_string()));
        }

        info!(target: "tf runner", "Command: {} {}",
            tf_path.to_string_lossy().blue(),
            self.load.command.join(" ").blue(),
        );

        // start terraform with all required arguments
        let mut tf_command = Command::new(&tf_path);

        let mut socket: Option<TcpListener> = None;
        // check if another instance is running with init and wait for it to finish
        if matches!(&self.load.command.as_slice(), [cmd, ..] if cmd == "init") {
            let delay = rand::rng().random_range(800..1200);

            loop {
                match TcpListener::bind(("0.0.0.0", self.load.params.get_lock_port())) {
                    Ok(listener) => {
                        socket = Some(listener);
                        break;
                    }
                    Err(_) => {
                        info!(target: "tf runner", "Waiting for unlock while init in parallel");
                        std::thread::sleep(std::time::Duration::from_millis(delay));
                    }
                }
            }
        };

        debug!(target: "tf runner", "Extra args: {}", &tf_args.join(" ").blue());

        let mut child = tf_command
            .current_dir(self.load.unit.temp_folder.to_str().unwrap())
            .args(&self.load.command)
            .args(tf_args)
            .envs(self.get_env_tf_vars())
            //.env("TF_DATA_DIR", &self.config.temp_folder_path)
            //.env("TF_PLUGIN_CACHE_DIR", "~/.terraform.d/plugin-cache")
            //.env("TF_DATA_DIR", &self.config.temp_folder_path)
            //.env("TF_CLI_ARGS", "-compact-warnings")
            // TODO: implement different exit status configuration only for apply and plan commands:
            //.env("TF_CLI_ARGS","-detailed-exitcode")
            .env("TF_IN_AUTOMATION", "true")
            .env("TF_INPUT", "0")
            .spawn()
            .unwrap_or_exit(format!(
                "Failed to start {:?} with args {:?}",
                tf_path, &self.load.command
            ));

        let result = child
            .wait()
            .unwrap_or_exit("Failed to get terraform exitcode".to_string());

        let exit_code = result.code().unwrap_or(1);

        // Use the common logger method from Runner trait
        self.logger(exit_code)?;

        if socket.is_some() {
            debug!(target: "tf runner", "Unlocking parallel run after finishing init command");
            drop(socket);
        }

        if !GLOBAL_CFG.clean_cache {
            debug!(target: "tf runner", "Ignore cache cleaning due to global config");
            return Ok(());
        }

        if exit_code == 0 {
            if let Some(first_command) = self.load.command.first() {
                if first_command == "apply"
                    || self
                        .load
                        .command
                        .contains(&"--detailed-exitcode".to_owned())
                {
                    debug!(target: "tf runner", "Remove temp folder after successful {} command", "apply".blue());
                    self.load.unit.remove_temp_folder();
                }
            }
        }
        Ok(())
    }

    /// TF-specific logger method that can be customized for Terraform operations
    /// 
    /// # Behavior
    /// - If `GLOBAL_CFG.dlog_db.is_some()`: Saves to configured database
    /// - If `GLOBAL_CFG.dlog_db.is_none()`: Saves to disk at `~/.cubtera/{org}/{unit}/{dims}/dlog.json`
    /// - Can be overridden for TF-specific logging features like state information
    /// 
    /// # Arguments
    /// * `exit_code` - The exit code from the Terraform command execution
    /// 
    /// # Returns
    /// * `Ok(())` - If logging was successful
    /// * `Err(Box<dyn std::error::Error>)` - If logging failed
    // TF runner can override logger method for custom logging logic
    // Currently uses default implementation but can be customized if needed
    fn logger(&mut self, exit_code: i32) -> Result<(), Box<dyn std::error::Error>> {
        debug!(target: "tf runner", "TF-specific logger method (can be customized)");
        
        // For now, use the default implementation
        // This can be overridden with TF-specific logging if needed:
        // - Special database fields for TF operations
        // - TF-specific log formats  
        // - Additional TF state information
        
        // Call the default logger implementation
        self.update_ctx("logger", json!("tf_runner_executed"));
        
        // Log to database if configured and dlog_db is available
        if GLOBAL_CFG.dlog_db.is_some() {
            use crate::core::dlog::Dlog;
            
            // TF runner can have special command type handling
            let command_type = self.get_load().command
                .first()
                .map(|s| s.as_str())
                .unwrap_or("unknown");
                
            let dlog = Dlog::build(self.get_load().unit.clone(), command_type.into(), exit_code);
            let _ = dlog
                .put(&GLOBAL_CFG.org)
                .check_with_warn("Can't put dlog to DB");
            info!(target: "tf runner", "TF Dlog data was saved for {} command", command_type);
        } else {
            // Save to disk if no dlog_db configuration
            use crate::core::dlog::Dlog;
            use std::path::Path;
            
            // Get command type from the first command argument
            let command_type = self.get_load().command
                .first()
                .map(|s| s.as_str())
                .unwrap_or("unknown");
            
            // Build dlog data same as for DB
            let dlog = Dlog::build(self.get_load().unit.clone(), command_type.into(), exit_code);
            
            // Create disk path: ~/.cubtera/ + same path structure as temp_folder
            let home_dir = std::env::var("HOME")
                .unwrap_or_else(|_| "/tmp".to_string());
            
            // Get relative path from temp_folder (remove temp_folder_path prefix)
            let temp_folder = &self.get_load().unit.temp_folder;
            let temp_folder_path = Path::new(&GLOBAL_CFG.temp_folder_path);
            
            let relative_path = if let Ok(rel_path) = temp_folder.strip_prefix(temp_folder_path) {
                rel_path.to_path_buf()
            } else {
                // Fallback: construct path manually if strip_prefix fails
                Path::new(&GLOBAL_CFG.org)
                    .join(&self.get_load().unit.name)
                    .join(self.get_load().unit.get_unit_state_path())
            };
            
            // Create dlog file path: ~/.cubtera/{relative_path}/dlog.json
            let dlog_dir = Path::new(&home_dir)
                .join(".cubtera")
                .join(relative_path);
            
            let dlog_file_path = dlog_dir.join("dlog.json");
            
            // Create directory if it doesn't exist
            std::fs::create_dir_all(&dlog_dir)?;
            
            // Serialize dlog to JSON and save to file
            let dlog_json = serde_json::to_string_pretty(&dlog)?;
            std::fs::write(&dlog_file_path, dlog_json)?;
            
            info!(target: "tf runner", "TF Dlog data was saved to disk: {:?} for {} command", dlog_file_path, command_type);
        }
        
        self.update_ctx("exit_code", json!(exit_code));
        debug!(target: "tf runner", "TF Final context: {}", self.get_ctx().to_string());

        Ok(())
    }
}

impl TfRunner {
    fn get_env_tf_vars(&self) -> HashMap<String, String> {
        // get all env vars started with TF_VAR_
        let mut env_vars: HashMap<String, String> = std::env::vars()
            .filter(
                |(k, _)| k.starts_with("TF_VAR_"),
            )
            .collect();

        env_vars.insert("TF_VAR_org_name".into(), GLOBAL_CFG.org.clone());
        env_vars.insert("TF_VAR_unit_name".into(), self.load.unit.name.clone());
        env_vars.insert("TF_VAR_dim_tree".into(), self.load.unit.get_unit_state_path());

        let kids: Vec<_> = self.load.unit.dimensions
            .iter()
            .filter_map(|dim| dim.kids.clone())
            .flatten()
            .collect();

        if !kids.is_empty() {
            env_vars.insert("TF_VAR_dim_kids".into(), kids.join(", "));
        }

        // add S3 state backend vars (LEGACY)
        if let Some(state) = self.load.state_backend.get("s3") {
            env_vars.insert("TF_VAR_tf_state_s3bucket".into(), state.get("bucket")
                .and_then(|b| b.as_str())
                .unwrap_or_default()
                .to_string()
            );
            env_vars.insert("TF_VAR_tf_state_s3region".into(), state.get("region")
                .and_then(|b| b.as_str())
                .unwrap_or_default()
                .to_string()
            );
            env_vars.insert("TF_VAR_tf_state_s3key".into(), state.get("key")
                .and_then(|b| b.as_str())
                .unwrap_or_default()
                .to_string()
            );
        }

        env_vars
    }

    fn create_state_backend(&self) -> Result<(), Box<dyn std::error::Error>> {
        // create tf backend config hcl file
        let tf_hcl = json!({
            "terraform": {
                "backend": &self.load.state_backend
            }
        });

        let path = self.load.unit.temp_folder.join("cubtera_backend.tf");
        convert_json_to_hcl_file(&tf_hcl, path)?;

        Ok(())
    }

    fn tf_vars_args(&self) -> Vec<String> {
        let mut tf_vars_args: Vec<String> = Vec::new();
        // extend vars with required env vars from unit manifest
        if let Some(spec) = &self.load.unit.manifest.spec {
            if let Some(env_vars) = &spec.env_vars {
                if let Some(required) = &env_vars.required {
                    for var in required {
                        tf_vars_args.extend([
                            "-var".to_string(),
                            format!(
                                "{}={}",
                                var.0,
                                std::env::var(var.1).unwrap_or_exit(format!("Required {}", var.1))
                            ),
                        ]);
                    }
                };
                if let Some(optional) = &env_vars.optional {
                    for var in optional {
                        if let Ok(env_var_value) = std::env::var(var.1) {
                            tf_vars_args
                                .extend(["-var".to_string(), format!("{}={env_var_value}", var.0)]);
                        }
                    }
                }
            }
        }

        tf_vars_args
    }
}

fn json_to_hcl(json: &Value, indent: usize) -> String {
    match json {
        Value::Object(map) => {
            let mut result = String::new();
            for (key, value) in map {
                let indentation = "  ".repeat(indent);
                match value {
                    Value::Object(inner_map) => {
                        if key == "backend" && inner_map.len() == 1 {
                            // Special handling for any backend type
                            let (backend_type, backend_config) = inner_map.iter().next().unwrap();
                            result.push_str(&format!(
                                "{}{}  \"{}\" {{\n",
                                indentation, key, backend_type
                            ));
                            result.push_str(&json_to_hcl(backend_config, indent + 1));
                            result.push_str(&format!("{}}}\n", indentation));
                        } else {
                            result.push_str(&format!("{}{} {{\n", indentation, key));
                            result.push_str(&json_to_hcl(value, indent + 1));
                            result.push_str(&format!("{}}}\n", indentation));
                        }
                    }
                    Value::Array(arr) => {
                        result.push_str(&format!("{}{} = [\n", indentation, key));
                        for item in arr {
                            result.push_str(&format!(
                                "{}  {},\n",
                                indentation,
                                json_to_hcl(item, indent + 1).trim()
                            ));
                        }
                        result.push_str(&format!("{}]\n", indentation));
                    }
                    _ => {
                        result.push_str(&format!(
                            "{}{} = {}\n",
                            indentation,
                            key,
                            json_to_hcl(value, indent)
                        ));
                    }
                }
            }
            result
        }
        Value::Array(arr) => {
            format!(
                "[{}]",
                arr.iter()
                    .map(|v| json_to_hcl(v, indent))
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        }
        Value::String(s) => format!("\"{}\"", s),
        Value::Number(n) => n.to_string(),
        Value::Bool(b) => b.to_string(),
        Value::Null => "null".to_string(),
    }
}

fn convert_json_to_hcl_file(json: &Value, output_file: PathBuf) -> std::io::Result<()> {
    let hcl_content = json_to_hcl(json, 0);
    std::fs::write(output_file, hcl_content.as_bytes())?;
    Ok(())
}

#[cfg(test)]
mod logger_tests;
