[package]
name = "cubtera-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Cubtera application layer - services and ports"

[dependencies]
cubtera-domain.workspace = true
cubtera-kernel.workspace = true

thiserror.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

