on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'

permissions:
    contents: write
    pull-requests: write

name: Code changes test
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Pre-build install dependencies
        run: |
          sudo apt update
          sudo apt install -y -qq libssl-dev pkg-config musl-tools 
          sudo update-ca-certificates
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          export PATH=$PATH:$HOME/.cargo/bin
          rustup target add x86_64-unknown-linux-musl

      - name: Generate Cargo.lock
        run: |
          cargo generate-lockfile

#      - name: Rust cache
#        uses: actions/cache@v4
#        with:
#          path: |
#            ~/.cargo/bin/
#            ~/.cargo/registry/index/
#            ~/.cargo/registry/cache/
#            ~/.cargo/git/db/
#            target/
#          key: linux-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build and test
        run: |
          cargo test --target x86_64-unknown-linux-musl